#!/usr/bin/env bash
# n8n Railway template (BM3 #1): Railway-like stack in a FRESH VM (compose.test.yaml = the template's variables).
set -uo pipefail
VM=${TESTVM:?set TESTVM to your throwaway-VM helper script}; H=$(cd "$(dirname "$0")" && pwd); OUT=$H/VM_TEST_RESULT.txt; : > "$OUT"
s() { "$VM" ssh "$1" >> "$OUT" 2>&1; echo "== $2 rc=$?" | tee -a "$OUT"; }
trap '"$VM" down >/dev/null 2>&1' EXIT
"$VM" up >> "$OUT" 2>&1 || { echo "VM up failed" | tee -a "$OUT"; exit 1; }
tar -C "$H" -czf /tmp/n8n-tpl-$$.tgz Dockerfile start.sh compose.test.yaml && "$VM" put /tmp/n8n-tpl-$$.tgz /home/learner/tpl.tgz; rm -f /tmp/n8n-tpl-$$.tgz
U='curl -s -c /tmp/cj -b /tmp/cj'
s "sudo apt-get update -qq && sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq docker.io docker-compose-v2 docker-buildx curl jq >/dev/null && mkdir -p tpl && tar -xzf tpl.tgz -C tpl && sudo docker version --format '{{.Server.Version}}'" prereq
s "cd tpl && sudo install -d -o root -g root -m 0755 n8nvol-rootowned && stat -c 'volume owner before: %U %a' n8nvol-rootowned && sudo docker compose -f compose.test.yaml build -q && sudo docker compose -f compose.test.yaml up -d 2>&1 | tail -2; for i in \$(seq 1 90); do curl -fs http://127.0.0.1:5678/healthz >/dev/null && break; sleep 3; done; curl -s http://127.0.0.1:5678/healthz; echo; sudo docker compose -f compose.test.yaml exec -T n8n n8n --version" up
s "for i in \$(seq 1 60); do curl -s http://127.0.0.1:5678/rest/settings | jq -e .data >/dev/null 2>&1 && break; sleep 3; done; curl -s http://127.0.0.1:5678/rest/settings | jq -c '{setup: .data.userManagement.showSetupOnFirstLoad, ver: .data.versionCli}' || curl -s http://127.0.0.1:5678/rest/settings | head -c 200" setup-closed
s "$U -w '  <- wrong-pw HTTP %{http_code}\n' -H 'Content-Type: application/json' -d '{\"emailOrLdapLoginId\":\"owner@example.test\",\"password\":\"wrong-password-000\"}' http://127.0.0.1:5678/rest/login | head -c 300; echo; $U -w '  <- right-pw HTTP %{http_code}\n' -H 'Content-Type: application/json' -d '{\"emailOrLdapLoginId\":\"owner@example.test\",\"password\":\"owner-test-pw-1234\"}' http://127.0.0.1:5678/rest/login | head -c 400; echo; $U http://127.0.0.1:5678/rest/login | head -c 300; echo '  <- GET /rest/login (who am I)'" login
s "cd tpl && sudo docker compose -f compose.test.yaml exec -T n8n sh -c 'printf %s \"[{\\\"id\\\":\\\"tplHook000001\\\",\\\"name\\\":\\\"hook\\\",\\\"active\\\":true,\\\"settings\\\":{},\\\"connections\\\":{\\\"Webhook\\\":{\\\"main\\\":[[{\\\"node\\\":\\\"Set\\\",\\\"type\\\":\\\"main\\\",\\\"index\\\":0}]]}},\\\"nodes\\\":[{\\\"parameters\\\":{\\\"path\\\":\\\"ping\\\",\\\"responseMode\\\":\\\"lastNode\\\",\\\"options\\\":{}},\\\"name\\\":\\\"Webhook\\\",\\\"type\\\":\\\"n8n-nodes-base.webhook\\\",\\\"typeVersion\\\":2,\\\"position\\\":[0,0],\\\"webhookId\\\":\\\"ping-0001\\\"},{\\\"parameters\\\":{\\\"assignments\\\":{\\\"assignments\\\":[{\\\"id\\\":\\\"a\\\",\\\"name\\\":\\\"pong\\\",\\\"value\\\":\\\"from worker\\\",\\\"type\\\":\\\"string\\\"}]},\\\"options\\\":{}},\\\"name\\\":\\\"Set\\\",\\\"type\\\":\\\"n8n-nodes-base.set\\\",\\\"typeVersion\\\":3.4,\\\"position\\\":[200,0]}]}]\" > /tmp/w.json && n8n import:workflow --input=/tmp/w.json && n8n publish:workflow --id=tplHook000001 2>&1 | tail -1' ; sudo docker compose -f compose.test.yaml restart n8n >/dev/null; for i in \$(seq 1 60); do curl -fs http://127.0.0.1:5678/healthz >/dev/null && break; sleep 3; done; sleep 8; for i in 1 2 3 4 5; do r=\$(curl -s -m 30 http://127.0.0.1:5678/webhook/ping); [ -n \"\$r\" ] && break; sleep 5; done; echo \"webhook: \$r\"; sudo docker compose -f compose.test.yaml logs worker 2>&1 | grep -i -E 'worker|job|finished' | tail -4 | cut -c1-160" queue-webhook
s "cd tpl && $U -H 'Content-Type: application/json' -d '{\"emailOrLdapLoginId\":\"owner@example.test\",\"password\":\"owner-test-pw-1234\"}' -w '  <- login-after-restart HTTP %{http_code}\n' http://127.0.0.1:5678/rest/login | head -c 200; echo; echo bWU9JCQ7IG49MDsgaD0wOyBiYWQ9MDsgZm9yIGQgaW4gL3Byb2MvWzAtOV0qOyBkbyBwPSR7ZCMvcHJvYy99OyBbICIkcCIgPSAiJG1lIiBdICYmIGNvbnRpbnVlOyBbIC1lICIkZC9lbnZpcm9uIiBdIHx8IGNvbnRpbnVlOyB1PSQoYXdrICcvXlVpZDove3ByaW50ICQyfScgIiRkL3N0YXR1cyIgMj4vZGV2L251bGwpOyBjPSQoY2F0ICIkZC9jb21tIiAyPi9kZXYvbnVsbCk7IGlmIGU9JCh0ciAnXDAnICdcbicgPCAiJGQvZW52aXJvbiIgMj4vZGV2L251bGwpOyB0aGVuIHg9MDsgcHJpbnRmICclc1xuJyAiJGUiIHwgZ3JlcCAtcSAnXk44Tl9PV05FUl9QQVNTV09SRD0nICYmIHg9MTsgZWxzZSB4PXVucmVhZGFibGU7IGZpOyBlY2hvICJwcm9jIHBpZD0kcCB1aWQ9JHUgY29tbT0kYyBoYXNfcHc9JHgiOyBpZiBbICIkdSIgPSAiMTAwMCIgXTsgdGhlbiBuPSQoKG4rMSkpOyBjYXNlICR4IGluIDApIDs7IDEpIGg9JCgoaCsxKSk7OyAqKSBiYWQ9JCgoYmFkKzEpKTs7IGVzYWM7IGZpOyBkb25lOyBbICIkKGlkIC11KSIgPSAxMDAwIF0gfHwgeyBlY2hvICdQTEFJTlBXLUNIRUNLLUZBSUwgY2hlY2tlciBub3QgdWlkIDEwMDAnOyBleGl0IDA7IH07IHIxPSQoY2F0IC9wcm9jLzEvZW52aXJvbiA+L2Rldi9udWxsIDI+JjEgJiYgZWNobyByZWFkYWJsZSB8fCBlY2hvIGRlbmllZCk7IGVjaG8gInVpZDEwMDAgcmVhZGluZyBwaWQxIGVudjogJHIxIjsgaWYgWyAiJG4iIC1nZSAyIF0gJiYgWyAiJGgiIC1lcSAwIF0gJiYgWyAiJGJhZCIgLWVxIDAgXSAmJiBbICIkcjEiID0gImRlbmllZCIgXTsgdGhlbiBlY2hvICJQTEFJTlBXLUNIRUNLLU9LIHVpZDEwMDBfc2Nhbm5lZD0kbiBoaXRzPTAiOyBlbHNlIGVjaG8gIlBMQUlOUFctQ0hFQ0stRkFJTCB1aWQxMDAwX3NjYW5uZWQ9JG4gaGl0cz0kaCB1bnJlYWRhYmxlPSRiYWQgcGlkMT0kcjEiOyBmaQ== | base64 -d > /tmp/pwchk.sh && sudo docker compose -f compose.test.yaml exec -T -u 1000 n8n sh -c 'sleep 25 & sleep 2; env -u N8N_OWNER_PASSWORD sh -s' < /tmp/pwchk.sh | grep PLAINPW | sed 's/^/CONTROL-LEAK: /'; sleep 26; sudo docker compose -f compose.test.yaml exec -T -u 1000 n8n env -u N8N_OWNER_PASSWORD sh -s < /tmp/pwchk.sh; sudo docker compose -f compose.test.yaml top n8n | head -4; sudo docker compose -f compose.test.yaml top worker | head -3; stat -c 'volume owner now: %u' n8nvol-rootowned" after-restart
echo "done $(date -Is)" >> "$OUT"
