#!/usr/bin/env bash
# n8n Railway template (BM3 #1): Railway-like stack in a FRESH VM (compose.test.yaml = the template's variables).
set -uo pipefail
VM=${TESTVM:?set TESTVM to your throwaway-VM helper script}; H=$(cd "$(dirname "$0")" && pwd); OUT=$H/VM_TEST_RESULT.txt; : > "$OUT"
s() { "$VM" ssh "$1" >> "$OUT" 2>&1; echo "== $2 rc=$?" | tee -a "$OUT"; }
trap '"$VM" down >/dev/null 2>&1' EXIT
"$VM" up >> "$OUT" 2>&1 || { echo "VM up failed" | tee -a "$OUT"; exit 1; }
tar -C "$H" -czf /tmp/n8n-tpl-$$.tgz Dockerfile start.sh compose.test.yaml && "$VM" put /tmp/n8n-tpl-$$.tgz /home/learner/tpl.tgz; rm -f /tmp/n8n-tpl-$$.tgz
U='curl -s -c /tmp/cj -b /tmp/cj'
s "sudo apt-get update -qq && sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq docker.io docker-compose-v2 docker-buildx curl jq >/dev/null && mkdir -p tpl && tar -xzf tpl.tgz -C tpl && sudo docker version --format '{{.Server.Version}}'" prereq
s "cd tpl && sudo docker compose -f compose.test.yaml build -q && sudo docker compose -f compose.test.yaml up -d 2>&1 | tail -2; for i in \$(seq 1 90); do curl -fs http://127.0.0.1:5678/healthz >/dev/null && break; sleep 3; done; curl -s http://127.0.0.1:5678/healthz; echo; sudo docker compose -f compose.test.yaml exec -T n8n n8n --version" up
s "for i in \$(seq 1 60); do curl -s http://127.0.0.1:5678/rest/settings | jq -e .data >/dev/null 2>&1 && break; sleep 3; done; curl -s http://127.0.0.1:5678/rest/settings | jq -c '{setup: .data.userManagement.showSetupOnFirstLoad, ver: .data.versionCli}' || curl -s http://127.0.0.1:5678/rest/settings | head -c 200" setup-closed
s "$U -w '  <- wrong-pw HTTP %{http_code}\n' -H 'Content-Type: application/json' -d '{\"emailOrLdapLoginId\":\"owner@example.test\",\"password\":\"wrong-password-000\"}' http://127.0.0.1:5678/rest/login | head -c 300; echo; $U -w '  <- right-pw HTTP %{http_code}\n' -H 'Content-Type: application/json' -d '{\"emailOrLdapLoginId\":\"owner@example.test\",\"password\":\"owner-test-pw-1234\"}' http://127.0.0.1:5678/rest/login | head -c 400; echo; $U http://127.0.0.1:5678/rest/login | head -c 300; echo '  <- GET /rest/login (who am I)'" login
s "cd tpl && sudo docker compose -f compose.test.yaml exec -T n8n sh -c 'printf %s \"[{\\\"id\\\":\\\"tplHook000001\\\",\\\"name\\\":\\\"hook\\\",\\\"active\\\":true,\\\"settings\\\":{},\\\"connections\\\":{\\\"Webhook\\\":{\\\"main\\\":[[{\\\"node\\\":\\\"Set\\\",\\\"type\\\":\\\"main\\\",\\\"index\\\":0}]]}},\\\"nodes\\\":[{\\\"parameters\\\":{\\\"path\\\":\\\"ping\\\",\\\"responseMode\\\":\\\"lastNode\\\",\\\"options\\\":{}},\\\"name\\\":\\\"Webhook\\\",\\\"type\\\":\\\"n8n-nodes-base.webhook\\\",\\\"typeVersion\\\":2,\\\"position\\\":[0,0],\\\"webhookId\\\":\\\"ping-0001\\\"},{\\\"parameters\\\":{\\\"assignments\\\":{\\\"assignments\\\":[{\\\"id\\\":\\\"a\\\",\\\"name\\\":\\\"pong\\\",\\\"value\\\":\\\"from worker\\\",\\\"type\\\":\\\"string\\\"}]},\\\"options\\\":{}},\\\"name\\\":\\\"Set\\\",\\\"type\\\":\\\"n8n-nodes-base.set\\\",\\\"typeVersion\\\":3.4,\\\"position\\\":[200,0]}]}]\" > /tmp/w.json && n8n import:workflow --input=/tmp/w.json && n8n publish:workflow --id=tplHook000001 2>&1 | tail -1' ; sudo docker compose -f compose.test.yaml restart n8n >/dev/null; for i in \$(seq 1 60); do curl -fs http://127.0.0.1:5678/healthz >/dev/null && break; sleep 3; done; sleep 8; for i in 1 2 3 4 5; do r=\$(curl -s -m 30 http://127.0.0.1:5678/webhook/ping); [ -n \"\$r\" ] && break; sleep 5; done; echo \"webhook: \$r\"; sudo docker compose -f compose.test.yaml logs worker 2>&1 | grep -i -E 'worker|job|finished' | tail -4 | cut -c1-160" queue-webhook
s "cd tpl && $U -H 'Content-Type: application/json' -d '{\"emailOrLdapLoginId\":\"owner@example.test\",\"password\":\"owner-test-pw-1234\"}' -w '  <- login-after-restart HTTP %{http_code}\n' http://127.0.0.1:5678/rest/login | head -c 200; echo; sudo docker compose -f compose.test.yaml exec -T n8n sh -c 'echo n8n-process-has-plain-pw=\$(tr \\\\0 \\\\n < /proc/\$(pidof node | cut -d\" \" -f1)/environ | grep -c ^N8N_OWNER_PASSWORD=); echo timeout=\$N8N_RUNNERS_TASK_TIMEOUT unverified=\$N8N_UNVERIFIED_PACKAGES_ENABLED binmode=\$N8N_DEFAULT_BINARY_DATA_MODE webhook=\$WEBHOOK_URL'" after-restart
echo "done $(date -Is)" >> "$OUT"
